default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: aeltyif
  password: 123456
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ruby_blog_development

test:
  <<: *default
  database: ruby_blog_test

production:
  <<: *default
  database: ruby_blog_production
